name: sprobot build & test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: build an image first
        run: docker build . --file Dockerfile --tag sprobot-local-test
      
      - name: run tests against it
        run: docker run sprobot-local-test ls -R

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
        run: |
          docker buildx build --push \
            --tag sadbox/sprobot:latest \
            --platform linux/amd64,linux/arm64 .

